---
services:

############################
# MARIADB
############################
    
  db:
    image: mariadb:11.8
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tano1234
      - MYSQL_PASSWORD=tano1234
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=tano
    restart: always
    networks:
      - nextcloud-network

############################
# NEXTCLOUD
############################

  app:
    image: nextcloud
    container_name: app
    ports:
      - 8082:80
    links: 
      - db
    depends_on:
      - db
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=tano1234
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=tano
      - MYSQL_HOST=db
      - PHP_UPLOAD_LIMIT=16G
      - PHP_MEMORY_LIMIT=2048M
    restart: always
    networks:
      - nextcloud-network

############################
# CLOUDFLARED
############################

  nextcloud-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: nextcloud-tunnel
    environment:
      - TZ=America/New_York
    command: tunnel --no-autoupdate run --token eyJhIjoiODA3NzcxNjBhOTEwMDFhNWVkMGZkMDQyMTA3NWU3YTQiLCJ0IjoiZDFmNzhjODgtNTZmOC00ZTVmLWE3YjgtZjVhMGNlZmJkOGQ5IiwicyI6IlptSmlaR05oTVdZdFpHTXpNaTAwTkRKaUxUZ3haVFl0TWpBM09ERXlNRFkwWTJaayJ9
    restart: always
    networks:
      - nextcloud-network

volumes:
  nextcloud:

networks:
  nextcloud-network:
    driver: bridge
